#!/usr/bin/env node
/**
 * The tool catalog is the source of truth for what this server exposes. This writes
 * the three places that repeat it — docs/TOOLS.md, the README table, and the MCPB
 * manifest's tool list — so they cannot drift from the code.
 *
 *   npm run tools:sync    rewrite them
 *   npm run tools:check   fail if they are stale (CI)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { TOOL_CATALOG } from "../src/tools/catalog.js";
import type { CatalogEntry, ToolCategory, ToolSurface } from "../src/tools/spec.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const SURFACES: Array<{ key: ToolSurface; heading: string; blurb: string }> = [
  {
    key: "psa",
    heading: "ConnectWise PSA (Manage)",
    blurb: "Always registered. Tickets, companies, contacts, assets, time, expenses, projects, finance, sales.",
  },
  {
    key: "automate",
    heading: "ConnectWise Automate (RMM)",
    blurb: "Registered only when `CW_AUTOMATE_*` is configured.",
  },
  {
    key: "control",
    heading: "ConnectWise Control (ScreenConnect) — beta",
    blurb: "Registered only when `CW_SCREENCONNECT_*` is configured.",
  },
];

const CATEGORY_LABEL: Record<ToolCategory, string> = {
  read: "Read-only",
  write: "Write",
  interactive: "Interactive",
};

function countBy(category: ToolCategory): number {
  return TOOL_CATALOG.filter((tool) => tool.category === category).length;
}

function table(tools: CatalogEntry[]): string {
  const rows = tools.map(
    (tool) => `| \`${tool.name}\` | ${tool.title} | ${CATEGORY_LABEL[tool.category]} | ${tool.summary} |`,
  );
  return ["| Tool | Shows as | Kind | What it does |", "| --- | --- | --- | --- |", ...rows].join("\n");
}

function toolSections(): string {
  return SURFACES.map(({ key, heading, blurb }) => {
    const tools = TOOL_CATALOG.filter((tool) => tool.surface === key);
    return `### ${heading}\n\n${blurb}\n\n${table(tools)}`;
  }).join("\n\n");
}

function summaryLine(suffix = "."): string {
  return `${TOOL_CATALOG.length} tools: ${countBy("read")} read-only, ${countBy("write")} write, ${countBy(
    "interactive",
  )} interactive${suffix}`;
}

const GENERATED_BLOCK = `${summaryLine()}\n\n${toolSections()}`;

function replaceBlock(source: string, marker: string, block: string): string {
  const begin = `<!-- BEGIN GENERATED ${marker} -->`;
  const end = `<!-- END GENERATED ${marker} -->`;
  const pattern = new RegExp(`${begin}[\\s\\S]*?${end}`);
  if (!pattern.test(source)) {
    throw new Error(`Missing ${begin} / ${end} markers`);
  }
  return source.replace(pattern, `${begin}\n\n${block}\n\n${end}`);
}

const TOOLS_DOC = `<!-- Generated by npm run tools:sync. Edit src/tools/*.ts, not this file. -->

# Tools

Every tool is named \`cw_\` + snake_case on the wire and shows a Title Case name in clients that
display one. The **Kind** column is what the tool's MCP annotations say about it:

- **Read-only** — \`readOnlyHint: true\`. Hosts can run these without a confirmation prompt, and
  Claude may call several in parallel.
- **Write** — \`readOnlyHint: false\`. These change live ConnectWise data. The raw \`*_api_write\`
  tools also carry \`_meta["anthropic/requiresUserInteraction"]\`, so Claude Code asks a person
  every single time and offers no "don't ask again".
- **Interactive** — a read or write tool that additionally declares an MCP Apps \`ui://\` resource
  and returns \`structuredContent\`, so supporting hosts render a card instead of JSON. Hosts
  without MCP Apps get the same JSON as any other tool.

<!-- BEGIN GENERATED TOOLS -->

${GENERATED_BLOCK}

<!-- END GENERATED TOOLS -->

## Interactive surface

\`cw_get_ticket\` declares \`ui://connectwise-manage/ticket-card\` under both the MCP Apps key
(\`_meta.ui.resourceUri\`) and the ChatGPT alias (\`_meta["openai/outputTemplate"]\`). The card is a
single self-contained HTML document — no CDN, no network — that renders the ticket, its recent
notes, and a box that posts an internal note back through \`cw_add_ticket_note\`. That note tool
carries \`_meta.ui.visibility: ["model", "app"]\` (and the \`openai/widgetAccessible\` alias), which
is what allows a card, rather than the model, to call it.

MCP Apps is an optional, negotiated extension (\`io.modelcontextprotocol/ui\`), so host support
varies. Nothing depends on it: the same tool result carries the full JSON in \`content\`.
`;

function manifestTools(): Array<{ name: string; description: string }> {
  return TOOL_CATALOG.map((tool) => ({
    name: tool.name,
    description: tool.category === "write" ? `${tool.summary} — writes to ConnectWise` : tool.summary,
  }));
}

interface Target {
  path: string;
  next: string;
}

function targets(): Target[] {
  const readmePath = join(ROOT, "README.md");
  const manifestPath = join(ROOT, "manifest.json");

  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>;
  manifest.tools = manifestTools();

  return [
    { path: join(ROOT, "docs/TOOLS.md"), next: TOOLS_DOC },
    {
      path: readmePath,
      next: replaceBlock(readFileSync(readmePath, "utf8"), "TOOLS", GENERATED_BLOCK),
    },
    { path: manifestPath, next: `${JSON.stringify(manifest, null, 2)}\n` },
  ];
}

const stale: string[] = [];
for (const target of targets()) {
  const current = (() => {
    try {
      return readFileSync(target.path, "utf8");
    } catch {
      return null;
    }
  })();
  if (current === target.next) continue;
  if (check) {
    stale.push(target.path.replace(`${ROOT}/`, ""));
    continue;
  }
  writeFileSync(target.path, target.next);
  console.log(`updated ${target.path.replace(`${ROOT}/`, "")}`);
}

if (check && stale.length > 0) {
  console.error(`Stale generated files: ${stale.join(", ")}. Run: npm run tools:sync`);
  process.exit(1);
}
if (check) console.log(`Tool docs match the catalog — ${summaryLine()}`);
